//AUTH
export const FIELD_EMAIL_CHANGED = "FIELD_EMAIL_CHANGED";
export const FIELD_PASSWORD_CHANGED = "FIELD_PASSWORD_CHANGED";
export const LOGIN_REQUEST_STARTED = 'LOGIN_REQUEST_STARTED';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const AUTH_STATE_RESET = "AUTH_STATE_RESET";

//JOBS
export const JOBS_REQUEST_STARTED = "JOBS_REQUEST_STARTED";
export const JOBS_REQUEST_FAILED = "JOBS_REQUEST_FAILED";
export const JOBS_REQUEST_SUCCESS = "JOBS_REQUEST_SUCCESS";
